require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/second_demos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SecondDemo. As you add validations to SecondDemo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SecondDemo.create! valid_attributes
      get second_demos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      second_demo = SecondDemo.create! valid_attributes
      get second_demo_url(second_demo)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_second_demo_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      second_demo = SecondDemo.create! valid_attributes
      get edit_second_demo_url(second_demo)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SecondDemo" do
        expect {
          post second_demos_url, params: { second_demo: valid_attributes }
        }.to change(SecondDemo, :count).by(1)
      end

      it "redirects to the created second_demo" do
        post second_demos_url, params: { second_demo: valid_attributes }
        expect(response).to redirect_to(second_demo_url(SecondDemo.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SecondDemo" do
        expect {
          post second_demos_url, params: { second_demo: invalid_attributes }
        }.to change(SecondDemo, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post second_demos_url, params: { second_demo: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested second_demo" do
        second_demo = SecondDemo.create! valid_attributes
        patch second_demo_url(second_demo), params: { second_demo: new_attributes }
        second_demo.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the second_demo" do
        second_demo = SecondDemo.create! valid_attributes
        patch second_demo_url(second_demo), params: { second_demo: new_attributes }
        second_demo.reload
        expect(response).to redirect_to(second_demo_url(second_demo))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        second_demo = SecondDemo.create! valid_attributes
        patch second_demo_url(second_demo), params: { second_demo: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested second_demo" do
      second_demo = SecondDemo.create! valid_attributes
      expect {
        delete second_demo_url(second_demo)
      }.to change(SecondDemo, :count).by(-1)
    end

    it "redirects to the second_demos list" do
      second_demo = SecondDemo.create! valid_attributes
      delete second_demo_url(second_demo)
      expect(response).to redirect_to(second_demos_url)
    end
  end
end
